### PR TITLE
Reject bad preconditions

### LINKED ISSUE #114: decreases & require order
The documentation on `decreases` (§ Introduction > Program Termination) is very thin and doesn't specify the order relation of this statement w.r.t. `require`. My guess is that `require` should come first as some assumptions in `decreases` could depends on the precondition, but currently stainless doesn't reject code such as this one:

```scala
  def requireDecreaseWrongOrder[T](l1: List[T], l2: List[T], x: T): Boolean = {
    decreases(l1.size)
    require(l1.content == l2.content)
    (l1-x).content == (l2-x).content
  }.holds
```

Currently stainless emits the following counterexample that doesn't pass `--check-models`.

```
[Warning ] - Model leads to runtime error: Requirement did not hold @19:5
[ Error  ] Something went wrong. The model should have been valid, yet we got this:
[ Error  ]   x: T        -> T#7
[ Error  ]   l1: List[T] -> Cons[T](T#6, Nil[T]())
[ Error  ]   l2: List[T] -> Nil[T]()
[ Error  ] for formula ¬{
[ Error  ]   assert(size[T](l1) >= 0, "Measure not guaranteed positive")
[ Error  ]   require(content[T](l1) == content[T](l2))
[ Error  ]   content[T](-[T](l1, x)) == content[T](-[T](l2, x))
[ Error  ] }
```

Swap the `require` and `decreases` clauses and everything is valid.

Proposed action to resolve this action:
 1. Impose order with `require` first (this can be generalised to reject programs that contain `require` in a position that is not the first statement of a function/lambda).
 2. Update the documentation.
 3. Add regression tests.

(Credit to @czipobence for spotting this.)

### PR DESCRIPTION
**Pull request by mantognini**
Closes #114.

 1. Impose order with `require` followed by `decreases` (documentation is updated accordingly).
 2. Reject functions with multiple `require` or `decreases`, or any pre-condition in an unexpected position.
 3. Add regression tests.
 4. Bonus: reduced copy-paste in integration suite.

Note: the `def traverse` is quite general and should probably be moved to inox in the future if some other modules would benefit from it.

### CODE REVIEW

File: frontends/common/src/it/scala/stainless/ExtractionSuite.scala [hunk 1]
```diff
@@ -61,23 +63,32 @@ class ExtractionSuite extends FunSpec with inox.ResourceUtils with InputUtils {
...
+  // the TreeSanitizer.
   def testRejectAll(dir: String): Unit = {
     val (reporter, ctx, files) = testSetUp(dir)
 
     describe(s"Programs extraction in $dir") {
-      val tryPrograms = files map { f => f -> Try(loadFiles(ctx, List(f))._2) }
+      val tryPrograms = files map { f =>
+        f -> Try {
+          val program = loadFiles(ctx, List(f))._2
+          extraction.TreeSanitizer.check(program)
```
Comment (samarion) [inline frontends/common/src/it/scala/stainless/ExtractionSuite.scala]: Shouldn't we actually run the full extraction pipeline here?

Comment (mantognini) [reply frontends/common/src/it/scala/stainless/ExtractionSuite.scala]: Makes sense. The latest commit addresses this.
