### PR TITLE
Fix #1301 and #1302

### LINKED ISSUE #1301: Tuples/ADTs destruction generating errors
Here are some crashes/errors caused by tuple/ADT destruction (i.e. `val (x, y) = ...`).
The ones not relying on stainless' library (i.e. the ones about tuples) do compile&run fine in Scala 3.0.2.

## Top-level destruction
```scala
object Test {
  // Putting these inside a function makes it work
  def p: (Int, Int) = (1, 2)
  val (x, y) = p
}
```

<details>
<summary>stainless-stack-trace.txt</summary>
<code>
inox.package$FatalError: Cannot recover from missing dependencies
	at inox.package$FatalError$.apply(package.scala:24)
	at inox.Reporter.onFatal(Reporter.scala:43)
	at inox.Reporter.fatalError(Reporter.scala:54)
	at inox.Reporter.fatalError(Reporter.scala:111)
	at stainless.frontend.Recovery$.recover(Recovery.scala:110)
	at stainless.frontend.Preprocessing.transform(Preprocessing.scala:18)
	at stainless.frontend.SplitCallBack.$anonfun$6(SplitCallBack.scala:166)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.frontend.SplitCallBack$$anon$1.debug(SplitCallBack.scala:29)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:166)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.lang.Thread.run(Thread.java:750)
</code>
</details>

## Tuple type annotation
```scala
object Test {
  def f = {
    def p: (Int, Int) = (1, 2)
    val (x, y): (Int, Int) = p // Removing (Int, Int) makes it work
  }
}
```

<details>
<summary>stainless-stack-trace.txt</summary>
<code>
java.lang.ClassCastException: inox.ast.Types$TupleType cannot be cast to stainless.extraction.oo.Trees$ClassType
	at stainless.frontends.dotc.CodeExtraction.extractPattern(CodeExtraction.scala:955)
	at stainless.frontends.dotc.CodeExtraction.extractMatchCase(CodeExtraction.scala:986)
	at stainless.frontends.dotc.CodeExtraction.extractTree$$anonfun$15(CodeExtraction.scala:1631)
	at scala.collection.immutable.List.map(List.scala:246)
	at stainless.frontends.dotc.CodeExtraction.extractTree(CodeExtraction.scala:1631)
	at stainless.frontends.dotc.CodeExtraction.rec$2(CodeExtraction.scala:1124)
	at stainless.frontends.dotc.CodeExtraction.rec$2(CodeExtraction.scala:1105)
	at stainless.frontends.dotc.CodeExtraction.extractBlock(CodeExtraction.scala:1154)
	at stainless.frontends.dotc.CodeExtraction.extractTree(CodeExtraction.scala:1187)
	at stainless.frontends.dotc.CodeExtraction.extractTreeOrNoTree(CodeExtraction.scala:999)
	at stainless.frontends.dotc.CodeExtraction.extractFunction(CodeExtraction.scala:798)
	at stainless.frontends.dotc.CodeExtraction.extractStatic$$anonfun$1(CodeExtraction.scala:362)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at stainless.frontends.dotc.CodeExtraction.extractStatic(CodeExtraction.scala:396)
	at stainless.frontends.dotc.CodeExtraction.extractObject(CodeExtraction.scala:441)
	at stainless.frontends.dotc.CodeExtraction.extractStatic$$anonfun$1(CodeExtraction.scala:328)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at stainless.frontends.dotc.CodeExtraction.extractStatic(CodeExtraction.scala:396)
	at stainless.frontends.dotc.StainlessExtraction.liftedTree1$1(StainlessExtraction.scala:61)
	at stainless.frontends.dotc.StainlessExtraction.extractUnit(StainlessExtraction.scala:67)
	at stainless.frontends.dotc.DottyCompiler$ExtractionPhase.run(DottyCompiler.scala:43)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:303)
	at scala.collection.immutable.List.map(List.scala:250)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:304)
	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
	at dotty.tools.dotc.Run.compileSources(Run.scala:166)
	at dotty.tools.dotc.Run.compile(Run.scala:150)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
	at dotty.tools.dotc.Driver.process(Driver.scala:199)
	at dotty.tools.dotc.Driver.process(Driver.scala:167)
	at stainless.frontends.dotc.DottyDriver.run(DottyCompiler.scala:53)
	at stainless.frontends.dotc.DottyCompiler$$anon$1.onRun(DottyCompiler.scala:124)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:32)
	at java.lang.Thread.run(Thread.java:750)
</code>
</details>

## Elements type annotation
This just yields an error in the output
```scala
object Test {
  def f = {
    def p: (Int, Int) = (1, 2)
    val (x: Int, y: Int) = p // Again, removing type annotations solves the issue
  }
}
```
```shell
Test.scala:4:13: error: Invalid type TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Int) for .isInstanceOf
               val (x: Int, y: Int) = p
                       ^^^
Starting verification...
Verified: 0 / 0
 stainless summary              
..................................................................................
total: 0    valid: 0    (0 from cache) invalid: 0    unknown: 0    time:     0.0 
```

## The same with ADTs
These issues manifest with ADTs as well, e.g.
```scala
import stainless.collection.*

object Test {
  def l: List[Int] = List(0, 1, 2)
  val Cons(h: Int, t: List[Int]) = l
}
```

<details>
<summary>stainless-stack-trace.txt</summary>
<code>
inox.package$FatalError: Cannot recover from missing dependencies
	at inox.package$FatalError$.apply(package.scala:24)
	at inox.Reporter.onFatal(Reporter.scala:43)
	at inox.Reporter.fatalError(Reporter.scala:54)
	at inox.Reporter.fatalError(Reporter.scala:111)
	at stainless.frontend.Recovery$.recover(Recovery.scala:110)
	at stainless.frontend.Preprocessing.transform(Preprocessing.scala:18)
	at stainless.frontend.SplitCallBack.$anonfun$6(SplitCallBack.scala:166)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.frontend.SplitCallBack$$anon$1.debug(SplitCallBack.scala:29)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:166)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.lang.Thread.run(Thread.java:750)
</code>
</details>

### LINKED ISSUE #1302: `NoSuchElementException` in interaction between lambdas and "auto-tupling"
The following snippet compiles correctly in Scala 3.0.2, but crashes stainless.
```scala
import stainless.collection.*

object Test {
  def f(l: List[(BigInt, BigInt)]): Unit = {
    val _ = l.map(_._1).map( (x) => x )     // Works fine
    val _ = l.map(_._2).map( (y) => y )     // Works fine
    val _ = l.map{ case (x, y) => (x, y) }  // Works fine
    val _ = l.map( (x, y) => (x, y) )       // java.util.NoSuchElementException: key not found: def _$x: BigInt = x$1._1
    ()
  }
}
```

<details>
<summary>stainless-stack-trace.txt</summary>
<code>
java.util.NoSuchElementException: key not found: def _$x: BigInt = x$1._1
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:635)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.effects(EffectsAnalyzer.scala:143)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.effects$(EffectsAnalyzer.scala:86)
	at stainless.extraction.imperative.AntiAliasing$SymbolsAnalysis.effects(AntiAliasing.scala:44)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.getAliasedParams(EffectsAnalyzer.scala:149)
	at stainless.extraction.imperative.EffectsAnalyzer$EffectsAnalysis.getAliasedParams$(EffectsAnalyzer.scala:86)
	at stainless.extraction.imperative.AntiAliasing$SymbolsAnalysis.getAliasedParams(AntiAliasing.scala:44)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$imperative$AntiAliasing$$_$updateFunction$1(AntiAliasing.scala:122)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.$anonfun$12(AntiAliasing.scala:460)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:460)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:475)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.$anonfun$15(AntiAliasing.scala:502)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:502)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform$$anonfun$8(AntiAliasing.scala:546)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:546)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform$$anonfun$8(AntiAliasing.scala:546)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.extraction.imperative.AntiAliasing$TransformerImpl$1.transform(AntiAliasing.scala:546)
	at stainless.extraction.imperative.AntiAliasing.makeSideEffectsExplicit$1(AntiAliasing.scala:551)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$imperative$AntiAliasing$$_$updateFunction$1(AntiAliasing.scala:126)
	at stainless.extraction.imperative.AntiAliasing.extractFunction(AntiAliasing.scala:640)
	at stainless.extraction.imperative.AntiAliasing.extractFunction(AntiAliasing.scala:85)
	at stainless.extraction.CachingPhase.$anonfun$3$$anonfun$1(ExtractionPipeline.scala:102)
	at stainless.extraction.utils.ConcurrentCache.cached(ConcurrentCaches.scala:26)
	at stainless.extraction.ExtractionCaches$ExtractionCache.cached(ExtractionCaches.scala:165)
	at stainless.extraction.CachingPhase.$anonfun$1(ExtractionPipeline.scala:102)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:156)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.map(Iterable.scala:671)
	at scala.collection.IterableOps.map$(Iterable.scala:671)
	at scala.collection.AbstractIterable.map(Iterable.scala:919)
	at stainless.extraction.CachingPhase.extractSymbols(ExtractionPipeline.scala:102)
	at stainless.extraction.CachingPhase.extractSymbols$(ExtractionPipeline.scala:82)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$oo$CachingPhase$$super$extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.imperative.AntiAliasing.stainless$extraction$oo$CachingPhase$$super$extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.oo.CachingPhase.extractSymbols(ExtractionPipeline.scala:28)
	at stainless.extraction.oo.CachingPhase.extractSymbols$(ExtractionPipeline.scala:13)
	at stainless.extraction.imperative.AntiAliasing.extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.imperative.AntiAliasing.extractSymbols(AntiAliasing.scala:11)
	at stainless.extraction.CachingPhase.extract(ExtractionPipeline.scala:97)
	at stainless.extraction.CachingPhase.extract$(ExtractionPipeline.scala:82)
	at stainless.extraction.imperative.AntiAliasing.extract(AntiAliasing.scala:11)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$2$$anonfun$1(DebugPipeline.scala:136)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:93)
	at inox.utils.TimerStorage.run(Timer.scala:88)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$1(DebugPipeline.scala:136)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.extraction.utils.DebugPipeline.debug(DebugPipeline.scala:124)
	at stainless.extraction.utils.DebugPipeline.extract(DebugPipeline.scala:137)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:30)
	at stainless.ComponentRun.extract(Component.scala:87)
	at stainless.ComponentRun.extract$(Component.scala:47)
	at stainless.verification.VerificationRun.extract(VerificationComponent.scala:53)
	at stainless.ComponentRun.apply(Component.scala:97)
	at stainless.ComponentRun.apply$(Component.scala:47)
	at stainless.verification.VerificationRun.apply(VerificationComponent.scala:53)
	at stainless.frontend.SplitCallBack.$anonfun$8(SplitCallBack.scala:196)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:198)
	at stainless.frontend.SplitCallBack.$anonfun$7(SplitCallBack.scala:170)
	at stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:170)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.lang.Thread.run(Thread.java:750)
</code>
</details>

The error must come from the fact that the passed lambda has type `(BigInt, BigInt) => (BigInt, BigInt)`, whereas the function expects `((BigInt, BigInt)) => (BigInt, BigInt)` (notice the extra pair of parentheses). 

Note however that the following variation works just fine:
```scala
import stainless.collection.*

object Test {
  def f(l: List[(BigInt, BigInt)]): Unit = {
    val f: ((BigInt, BigInt)) => (BigInt, BigInt) = (x, y) => (x, y)
    val _ = l.map( f )
    ()
  }
}
```

### PR DESCRIPTION
**Pull request by mario-bucev**

### CODE REVIEW

File: frontends/benchmarks/dotty-specific/valid/i1302a.scala [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import stainless.collection._
+
+object i1302a {
+  def f(l: List[(BigInt, BigInt)]): Unit = {
+    val _ = l.map(_._1).map((x) => x) // Works fine
+    val _ = l.map(_._2).map((y) => y) // Works fine
+    val _ = l.map { case (x, y) => (x, y) } // Works fine
+    val _ = l.map((x, y) => (x, y)) // java.util.NoSuchElementException: key not found: def _$x: BigInt = x$1._1
```
Comment (vkuncak) [inline frontends/benchmarks/dotty-specific/valid/i1302a.scala:8]: Is the comment line still correct after this fix?

**Review by vkuncak — APPROVED** [review]

File: frontends/benchmarks/dotty-specific/valid/i1302a.scala (hunk 1 above)
Comment (mario-bucev) [reply frontends/benchmarks/dotty-specific/valid/i1302a.scala:8]: Good catch!
