### PR TITLE
Fix #1405

### LINKED ISSUE #1405: Type error: couldn't find function `IntAbsToBigInt`
The following snippet:
```scala
import stainless.lang._
import stainless.collection._

object i1405a {
  def compose(f: Int => Int, g: Int => Int) = (x: Int) => f(g(x))
  def iter(n: Int, f: Int => Int): Int => Int = {
    if (n < 0) f
    else
      n match {
        case 1 => f
        case 0 => f
        case _ =>
          val asdf = iter(n - 1, f)
          compose(f, asdf)
      }
  }
}
```
causes the following crash:
<details><summary>Click to expand</summary>

```
inox.ast.TypeOps$TypeErrorException: Type error: !(IntAbsToBigInt$0(_$g$1(x$122)) <= (0 + 0) + 0), expected Boolean,
found <untyped>

Typing explanation:
!(IntAbsToBigInt$0(_$g$1(x$122)) <= (0 + 0) + 0) is of type <untyped>
  IntAbsToBigInt$0(_$g$1(x$122)) <= (0 + 0) + 0 is of type <untyped>
    IntAbsToBigInt$0(_$g$1(x$122)) is of type <untyped>
      _$g$1(x$122) is of type Int
        _$g$1 is of type (Int) => Int
        x$122 is of type Int but couldn't find function IntAbsToBigInt$0
    (0 + 0) + 0 is of type BigInt
      0 + 0 is of type BigInt
        0 is of type BigInt
        0 is of type BigInt
      0 is of type BigInt
	at inox.ast.TypeOps$TypeErrorException$.apply(TypeOps.scala:29)
	at inox.ast.TypeOps.typeCheck(TypeOps.scala:89)
	at inox.ast.TypeOps.typeCheck$(TypeOps.scala:11)
	at inox.ast.SimpleSymbols$SimpleSymbols.typeCheck(SimpleSymbols.scala:12)
	at inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr$$anonfun$1$$anonfun$1(UnrollingSolver.scala:214)
	at inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr$$anonfun$1$$anonfun$adapted$1(UnrollingSolver.scala:215)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:84)
	at inox.utils.TimerStorage.run(Timer.scala:78)
	at inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr$$anonfun$1(UnrollingSolver.scala:215)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:84)
	at inox.utils.TimerStorage.run(Timer.scala:78)
	at inox.solvers.unrolling.AbstractUnrollingSolver.assertCnstr(UnrollingSolver.scala:242)
	at inox.solvers.SolverFactory$NativeZ3Impl$1.inox$tip$TipDebugger$$super$assertCnstr(SolverFactory.scala:175)
	at inox.tip.TipDebugger.assertCnstr(TipDebugger.scala:91)
	at inox.tip.TipDebugger.assertCnstr$(TipDebugger.scala:11)
	at inox.solvers.SolverFactory$NativeZ3Impl$1.assertCnstr(SolverFactory.scala:175)
	at inox.solvers.SolverFactory$NativeZ3Impl$1.assertCnstr(SolverFactory.scala:175)
	at inox.solvers.SimpleSolverAPI.solveVALID(SimpleSolverAPI.scala:21)
	at inox.solvers.SimpleSolverAPI.solveVALID$(SimpleSolverAPI.scala:6)
	at inox.solvers.SimpleSolverAPI$$anon$1.solveVALID(SimpleSolverAPI.scala:57)
	at stainless.termination.Strengthener.$anonfun$13(Strengthener.scala:157)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:690)
	at scala.collection.immutable.Map$.from(Map.scala:641)
	at scala.collection.immutable.Map$.from(Map.scala:171)
	at scala.collection.MapOps$WithFilter.map(Map.scala:381)
	at stainless.termination.Strengthener.strengthenApplications$$anonfun$3(Strengthener.scala:166)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
	at stainless.termination.Strengthener.strengthenApplications(Strengthener.scala:224)
	at stainless.termination.Strengthener.strengthenApplications$(Strengthener.scala:10)
	at stainless.termination.TerminationChecker$ProcessingPipelineImpl$1$IntegerOrderingImpl.strengthenApplications(TerminationChecker.scala:122)
	at stainless.termination.RelationProcessor.run$$anonfun$1(RelationProcessor.scala:30)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:84)
	at inox.utils.TimerStorage.run(Timer.scala:78)
	at stainless.termination.RelationProcessor.run(RelationProcessor.scala:108)
	at stainless.termination.ProcessingPipeline$$anon$3.next(ProcessingPipeline.scala:230)
	at stainless.termination.ProcessingPipeline$$anon$3.next(ProcessingPipeline.scala:225)
	at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:478)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
	at stainless.termination.ProcessingPipeline.runPipeline(ProcessingPipeline.scala:258)
	at stainless.termination.ProcessingPipeline.terminates(ProcessingPipeline.scala:158)
	at stainless.termination.ProcessingPipeline.terminates$(ProcessingPipeline.scala:9)
	at stainless.termination.TerminationChecker$ProcessingPipelineImpl$1.terminates(TerminationChecker.scala:115)
	at stainless.termination.MeasureInference$TransformerContext.$anonfun$3(MeasureInference.scala:130)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:84)
	at inox.utils.TimerStorage.run(Timer.scala:78)
	at stainless.termination.MeasureInference$TransformerContext.inferMeasure(MeasureInference.scala:131)
	at stainless.termination.MeasureInference.extractFunction(MeasureInference.scala:183)
	at stainless.termination.MeasureInference.$anonfun$8$$anonfun$1(MeasureInference.scala:199)
	at stainless.extraction.utils.ConcurrentCache.cached(ConcurrentCaches.scala:26)
	at stainless.extraction.ExtractionCaches$ExtractionCache.cached(ExtractionCaches.scala:165)
	at stainless.termination.MeasureInference.$anonfun$8(MeasureInference.scala:199)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.map(Iterable.scala:682)
	at scala.collection.IterableOps.map$(Iterable.scala:682)
	at scala.collection.AbstractIterable.map(Iterable.scala:933)
	at stainless.termination.MeasureInference.extractSymbols(MeasureInference.scala:199)
	at stainless.termination.MeasureInference.extractSymbols(MeasureInference.scala:194)
	at stainless.extraction.CachingPhase.extract(ExtractionPipeline.scala:126)
	at stainless.extraction.CachingPhase.extract$(ExtractionPipeline.scala:105)
	at stainless.termination.MeasureInference.extract(MeasureInference.scala:10)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$1$$anonfun$1(DebugPipeline.scala:139)
	at scala.util.Try$.apply(Try.scala:210)
	at inox.utils.TimerStorage.runAndGetTime(Timer.scala:84)
	at inox.utils.TimerStorage.run(Timer.scala:78)
	at stainless.extraction.utils.DebugPipeline.extract$$anonfun$1(DebugPipeline.scala:139)
	at stainless.extraction.utils.DebugSymbols.debug(DebugPipeline.scala:64)
	at stainless.extraction.utils.DebugSymbols.debug$(DebugPipeline.scala:29)
	at stainless.extraction.utils.DebugPipeline.debug(DebugPipeline.scala:127)
	at stainless.extraction.utils.DebugPipeline.extract(DebugPipeline.scala:140)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:48)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:47)
	at stainless.extraction.ExtractionPipeline$AndThenImpl$1.extract(ExtractionPipeline.scala:47)
	at stainless.ComponentRun.extract(Component.scala:75)
	at stainless.ComponentRun.extract$(Component.scala:35)
	at stainless.verification.VerificationRun.extract(VerificationComponent.scala:48)
	at stainless.ComponentRun.apply(Component.scala:85)
	at stainless.ComponentRun.apply$(Component.scala:35)
	at stainless.verification.VerificationRun.apply(VerificationComponent.scala:48)
	at stainless.frontend.SplitCallBack.$anonfun$10(SplitCallBack.scala:196)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at stainless.frontend.SplitCallBack.processFunctionsSymbols(SplitCallBack.scala:198)
	at stainless.frontend.SplitCallBack.$anonfun$9(SplitCallBack.scala:170)
	at stainless.extraction.utils.ConcurrentCache.getOrElseUpdate(ConcurrentCaches.scala:15)
	at stainless.frontend.SplitCallBack.processFunctions(SplitCallBack.scala:170)
	at stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:156)
	at stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:78)
	at stainless.frontend.ThreadedFrontend$$anon$1.run(ThreadedFrontend.scala:34)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

</details>

The fix is to move [this line](https://github.com/epfl-lara/stainless/blob/3963b68284088d4e3cbbf978fd390360329d8fbc/core/src/main/scala/stainless/termination/Strengthener.scala#L135) before [this one](https://github.com/epfl-lara/stainless/blob/3963b68284088d4e3cbbf978fd390360329d8fbc/core/src/main/scala/stainless/termination/Strengthener.scala#L156), the reason being that [`checker.terminates(fd)`](https://github.com/epfl-lara/stainless/blob/3963b68284088d4e3cbbf978fd390360329d8fbc/core/src/main/scala/stainless/termination/Strengthener.scala#L140) may add further definitions.

### PR DESCRIPTION
**Pull request by mario-bucev**
Close #1405

### CODE REVIEW

File: frontends/benchmarks/termination/valid/i1405a.scala [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+object i1405a {
+  def compose(f: Int => Int, g: Int => Int) = (x: Int) => f(g(x))
+  def iter(n: Int, f: Int => Int): Int => Int = {
+    if (n < 0) f
+    else
+      n match {
+        case 1 => f
+        case 0 => f
+        case _ =>
+          val asdf = iter(n - 1, f)
```
Comment (vkuncak) [inline frontends/benchmarks/termination/valid/i1405a.scala:13]: asdf = a symbol denoting fatigue

**Review by vkuncak — APPROVED** [review]

File: frontends/benchmarks/termination/valid/i1405a.scala (hunk 1 above)
Comment (mario-bucev) [reply frontends/benchmarks/termination/valid/i1405a.scala:13]: These benchmarks are from the OCaml translations, I've also forgot to mention that @drganam originally discovered the bug, not me.
